. .\set-deepseek-env.ps1 | Out-Null
$env:BILIBILI_COVERAGE_LOOP_MAX_CYCLES = '5'
$env:BILIBILI_HARVEST_MAX_QUERIES = '12'
$env:BILIBILI_HARVEST_INCLUDE_DANMAKU = '1'
$env:BILIBILI_CRAWLER_MIN_DELAY_MS = '2500'
$env:BILIBILI_CRAWLER_JITTER_MS = '2000'
npm run dictionary:auto
